apiVersion: v1
kind: ReplicationController
metadata:
  name: app
  labels:
    name: app
spec:
  replicas: 4
  selector:
    name: app
  template:
    metadata:
      labels:
        name: app
    spec:
      containers:
        - name: nginx
          image: hnarayanan/djangogirls-app:0.1
          ports:
            - containerPort: 8000
