apiVersion: v1
kind: ReplicationController
metadata:
  name: app-sqlite3
  labels:
    name: app
spec:
  replicas: 1
  selector:
    name: app
    database: sqlite3
  template:
    metadata:
      labels:
        name: app
        database: sqlite3
    spec:
      containers:
        - name: app
          image: hnarayanan/djangogirls-app:0.8
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 8000
