apiVersion: v1
kind: ReplicationController
metadata:
  name: app-postgres
  labels:
    name: app
spec:
  replicas: 1
  selector:
    name: app
    database: postgres
  template:
    metadata:
      labels:
        name: app
        database: postgres
    spec:
      containers:
        - name: app
          image: hnarayanan/djangogirls-app:1.1
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: DATABASE_NAME
              value: app_db
            # TODO: Use Kubernetes Secret objects to hold the following credentials
            - name: DATABASE_USER
              value: app_db_user
            - name: DATABASE_PASSWORD
              value: app_db_pw
          ports:
            - containerPort: 8000
