apiVersion: v1
kind: ReplicationController
metadata:
  name: webserver
  labels:
    name: webserver
spec:
  replicas: 4
  selector:
    name: webserver
  template:
    metadata:
      labels:
        name: webserver
    spec:
      containers:
        - name: nginx
          image: hnarayanan/nginx:1.9.11
          ports:
            - containerPort: 80
