apiVersion: v1
kind: ReplicationController
metadata:
  name: database
  labels:
    name: database
spec:
  replicas: 1
  selector:
    name: database
  template:
    metadata:
      labels:
        name: database
    spec:
      containers:
        - name: postgres
          image: hnarayanan/postgresql:9.5
          env:
            - name: DB_PASS
              value: password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pg-data
      volumes:
        - name: pg-data
          persistentVolumeClaim:
            claimName: pg-data-claim
